name: Run JaCoCo

on:
  push:
    branches:
      - main  # Adjust as necessary

jobs:
  run-jacoco:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: af43a3e71f2bdb4765294f7d6314b1428737849d  # Use the specific commit or branch

    - name: Set up JDK 17 for project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Modify POM.xml for JaCoCo Plugin and Surefire Configuration
      run: |
        if [ -f "pom.xml" ]; then
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            sed -i '{
              /<\/plugins>/i \
              <plugin> \
                  <groupId>org.jacoco</groupId> \
                  <artifactId>jacoco-maven-plugin</artifactId> \
                  <version>0.8.11</version> \
                  <executions> \
                      <execution> \
                          <goals> \
                              <goal>prepare-agent</goal> \
                          </goals> \
                      </execution> \
                      <execution> \
                          <id>report</id> \
                          <phase>test</phase> \
                          <goals> \
                              <goal>report</goal> \
                          </goals> \
                      </execution> \
                  </executions> \
              </plugin>' pom.xml

            sed -i '/<artifactId>maven-surefire-plugin<\/artifactId>/a \
              <configuration> \
                  <testFailureIgnore>true<\/testFailureIgnore> \
              <\/configuration>' pom.xml
          elif [[ ${{ matrix.os }} == 'macos-latest' ]]; then
            sed -i '' '/<\/plugins>/i \
              <plugin> \
                  <groupId>org.jacoco</groupId> \
                  <artifactId>jacoco-maven-plugin</artifactId> \
                  <version>0.8.11</version> \
                  <executions> \
                      <execution> \
                          <goals> \
                              <goal>prepare-agent</goal> \
                          </goals> \
                      </execution> \
                      <execution> \
                          <id>report</id> \
                          <phase>test</phase> \
                          <goals> \
                              <goal>report</goal> \
                          </goals> \
                      </execution> \
                  </executions> \
              </plugin>' pom.xml

            sed -i '' '/<artifactId>maven-surefire-plugin<\/artifactId>/a \
              <configuration> \
                  <testFailureIgnore>true<\/testFailureIgnore> \
              <\/configuration>' pom.xml
          fi
        else
          echo "pom.xml not found"
          exit 1
        fi

    - name: Build project with JDK 17
      run: mvn test

    - name: Checkout Export Repository
      uses: actions/checkout@v2
      with:
        repository: flaky-dynamic-testing/jacoco-exports
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy JaCoCo Reports to new repository
      run: |
        find . -type d -path "*/target/site/jacoco" | while IFS= read -r dir; do
            # Find .html and .xml files within each directory
            find "$dir" -type f \( -name "*.html" -o -name "*.xml" \) -exec cp {} $GITHUB_WORKSPACE/jacoco-reports \;
        done
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        mkdir -p jacoco-exports/jacoco-reports-for-$REPO_NAME
        cp -r $GITHUB_WORKSPACE/jacoco-report/* jacoco-exports/jacoco-reports-for-$REPO_NAME
        cd jacoco-exports
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "Add Jacoco reports for $REPO_NAME"
        git push origin main
