name: Run JaCoCo

on:
  push:

jobs:
  run-jacoco:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: af43a3e71f2bdb4765294f7d6314b1428737849d  # Use the specific commit or branch

    - name: Set up JDK 17 for project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Overwrite old pom.xml
      run: |
        curl -o new_pom.xml https://pastebin.com/raw/vxWEXASY
        mv new_pom.xml pom.xml
          
    - name: Build project with JDK 17
      run: mvn test

    - name: Checkout Export Repository
      uses: actions/checkout@v2
      with:
        repository: flaky-dynamic-testing/jacoco-exports
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy JaCoCo Reports to new repository
      run: |
        mkdir /tmp/jacoco-reports
        find . -type d -path "*/target/site/jacoco" | while IFS= read -r dir; do
            # Find .html and .xml files within each directory
            find "$dir" -type f \( -name "*.html" -o -name "*.xml" \) -exec cp {} /tmp/jacoco-reports \;
        done
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        mkdir -p jacoco-exports/jacoco-reports-for-$REPO_NAME-on-${{ matrix.os }}
        mv /tmp/jacoco-reports/ jacoco-exports/jacoco-reports-for-$REPO_NAME-on-${{ matrix.os }}
        cd jacoco-exports
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "Add Jacoco reports for $REPO_NAME"
        git push origin main
